django_rock/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    # landing page
    path('', include('home.urls')),
    # buisness logic
    path('hello/', include('hello_world.urls')),
    path('quotes/', include('quote_manager.urls')),
    path('conv/', include('converter.urls')),
    ### login/user
    # accounts/login/ [name='login']
    # accounts/logout/ [name='logout']
    # accounts/password_change/ [name='password_change']
    # accounts/password_change/done/ [name='password_change_done']
    # accounts/password_reset/ [name='password_reset']
    # accounts/password_reset/done/ [name='password_reset_done']
    # accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
    # accounts/reset/done/ [name='password_reset_complete']
    path('accounts/', include('django.contrib.auth.urls')), 
    # admin
    path('admin/', admin.site.urls),
]

django_rock/home/urls.py
from django.urls import path
from .views import home_view

urlpatterns = [
    path('', home_view, name='home')
]

django_rock/quote_manager/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', QuoteListView.as_view(), name="quote_list"),
    path('test', quotes_view),
    path('<int:pk>/', QuoteDetailView.as_view(), name="quote_detail"),
    path('create/', create_project_and_quote_request, name="quote_create"),
    path('<int:pk>/update', QuoteUpdateView.as_view(), name="quote_update"),
    path('<int:pk>/delete', QuoteDeleteView.as_view(), name="quote_delete"),
    
    # backlog
    path('backlog/', BacklogListView.as_view(), name="quote_backlog"),
    path('claimed/', list_claimed_request, name="quote_claimed"),
]

django_rock/quote_manager/models.py
from django.db import models

class ProjectModel(models.Model):
    address = models.CharField(max_length=255)
    # TODO: add auto address from postcode
    postcode = models.CharField(max_length=16, default="", blank=True)
    
    WORK_TYPE_CHOICES = [
        ("unknown", "Unknown"),
        ("tiling", "Tiling"),
        ("stone", "Stone"),
        ("joinery", "Joinery"),
        ("mixed", "Mixed"),
    ]
    work_type = models.CharField(
        max_length=255,
        choices=WORK_TYPE_CHOICES,
        default="unknown"
    )
    value = models.FloatField(default=0.0, blank=True)
    
    CONTRACT_TYPE_CHOICES = [
        ("unknown", "Unknown"),
        ("tender", "Tender"),
        ("contract", "Contract"),
    ]
    contract_type = models.CharField(
        max_length=255,
        choices=CONTRACT_TYPE_CHOICES,
        default="unknown",
    )
    
    # optional
    # TODO: consider replacing with custom user model
    estimater = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, blank=True, related_name="project_estimater")
    manager = models.ForeignKey("auth.User", on_delete=models.SET_NULL, null=True, blank=True, related_name="project_manager")
    
    # generated
    # TODO: add a created by to track who filled in the new quote
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    attractiveness = models.IntegerField(blank=True, null=True)
    multiplier = models.IntegerField(blank=True, null=True)
    chasability = models.IntegerField(blank=True, null=True)
    last_reminder_at = models.DateTimeField(blank=True, null=True)

### NOTE:
# currently company is dumped in the quote request as the only unique company info is the name
# not ideal but otherwise you have a dumb model
    
class QuoteModel(models.Model):
    # blank allows for empty strings or default values to be used
    # null allows for not setting a value
    
    # TODO: consider safety of using this?
    # on_delete=models.CASCADE means that if the project is deleted, the quote request is also deleted
    
    # required
    # TODO: add a created by to track who filled in the quote
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE)
    company = models.CharField(max_length=255, blank=False, null=False)
    contact_name = models.CharField(max_length=255, blank=False, null=False)
    contact_email = models.EmailField(blank=False, null=False)
    date_in = models.DateField(blank=False, null=False)
    QUOTE_STATE_CHOICES = [
        ("unknown", "Unknown"),
        ("incomplete", "Incomplete"),
        ("unclaimed", "Unclaimed"),
        ("in_progress", "In progress"),
        ("waiting_for_supplier", "Waiting for supplier"),
        ("waiting_for_client", "Waiting for client"),
        ("sent", "Sent"),
        ("to_chase", "To Chase"),
    ]
    state = models.CharField(max_length=255, choices=QUOTE_STATE_CHOICES, default="unknown", blank=False, null=False)
    state_updated_at = models.DateTimeField(blank=True, null=True)
    
    # optional
    contact_phone = models.CharField(max_length=16, blank=True, null=True)
    date_close = models.DateField(blank=True, null=True)
    date_sent = models.DateField(blank=True, null=True)
    BUISNESS_BY_CHOICES = [
        ("karl", "Karl"),
        ("scs", "SCS"),
    ]
    buisness_by = models.CharField(max_length=255, choices=BUISNESS_BY_CHOICES, blank=True, null=True)
    
    # generated
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    

class ProjectBlacklist(models.Model):
    # required
    project = models.ForeignKey(ProjectModel, on_delete=models.CASCADE)
    reason = models.CharField(max_length=255, blank=False, null=False)
    
    # generated
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Project Blacklist ({self.id}) - {self.project.address} ({self.project.id})"
    
    

class CompanyBlacklist(models.Model):
    # required
    company = models.CharField(max_length=255, blank=False, null=False)
    reason = models.CharField(max_length=255, blank=False, null=False)
    
    # generated
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"Company Blacklist ({self.id}) - {self.company}"
    

django_rock/quote_manager/forms.py
from django import forms
from .models import ProjectModel, QuoteModel

class ProjectForm(forms.ModelForm):
    
    class Meta:
        model = ProjectModel
        fields = ['address', 'postcode', 'work_type', 'contract_type', 'value', 'estimater', 'manager']



class QuoteForm(forms.ModelForm):
    
    class Meta:
        model = QuoteModel
        fields = ['company', 'date_in', 'date_close', 'date_sent', 'buisness_by', 'contact_name', 'contact_email', 'contact_phone', 'state', 'state_updated_at',]

django_rock/quote_manager/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse, Http404
from django.conf import settings
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

from .models import QuoteModel, ProjectModel, ProjectBlacklist, CompanyBlacklist
from .forms import ProjectForm, QuoteForm

# TODO: convert all url redirects to use correct look up namespacing e.g. my_app:my_view
# for redirect, reverse, reverse_lazy

def quotes_view(request):
    return HttpResponse("Hello, World!")
    
def create_project_and_quote_request(request):
    if request.method == 'POST':
        project_form = ProjectForm(request.POST)
        quote_form = QuoteForm(request.POST)
        
        if quote_form.is_valid() and project_form.is_valid():
            if project_form.is_valid():
                project = project_form.save()
                quote_request = quote_form.save(commit=False)
                quote_request.project = project
                quote_request.save()
            return redirect("quote_list")
    else:
        project_form = ProjectForm()
        quote_form = QuoteForm()
    
    return render(request, 'quote_manager/quote_create.html', {
        'project_list': ProjectModel.objects.all().order_by('address'),
        'project_form': project_form,
        'quote_form': quote_form
    })

@login_required
def list_claimed_request(request, *args, **kwargs):
    return render(request, 'quote_manager/quote_list.html', {
        'quote_list': QuoteModel.objects.filter(project__estimater=request.user)
    })
    

class BacklogListView(ListView):
    model = QuoteModel
    template_name = "quote_manager/quote_list.html"
    context_object_name = "quote_list"
    
    def get_queryset(self):
        return super().get_queryset().filter(project__estimater__isnull=True)
    

class QuoteListView(ListView):
    model = QuoteModel
    template_name = "quote_manager/quote_list.html"
    context_object_name = "quote_list"

class QuoteDetailView(DetailView):
    model = QuoteModel
    template_name = "quote_manager/quote_detail.html"
    context_object_name = "quote"
    
class QuoteCreateView(CreateView):
    model = QuoteModel
    template_name = "quote_manager/quote_create.html"
    fields = ["project", "company", "contact_name", "contact_email", "date_in", "contact_phone", "date_close", "date_sent",
    ]
    success_url = reverse_lazy("quote_manager:quote_list")
    
class QuoteUpdateView(UpdateView):
    model = QuoteModel
    template_name = "quote_manager/quote_update.html"
    fields = [
        "project",
        "company",
        "contact_name",
        "contact_email",
        "date_in",
        "contact_phone",
        "date_close",
        "date_sent",
    ]
    
class QuoteDeleteView(DeleteView):
    model = QuoteModel
    template_name = "quote_manager/quote_delete.html"
    success_url = reverse_lazy("quote_manager:quote_list")



##### PROJECT BLACKLIST #####
class ProjectBlacklistListView(ListView):
    model = ProjectBlacklist
    template_name = "quote_manager/project_blacklist_list.html"
    context_object_name = "blacklist_project_list"
    
class ProjectBlacklistDetailView(DetailView):
    model = ProjectBlacklist
    template_name = "quote_manager/project_blacklist_detail.html"
    context_object_name = "blacklist_project"

class ProjectBlacklistCreateView(CreateView):
    model = ProjectBlacklist
    template_name = "quote_manager/project_blacklist_create.html"
    fields = [
        "project",
        "reason",
    ]
    success_url = reverse_lazy("quote_manager:project_blacklist_list")
    
class ProjectBlacklistUpdateView(UpdateView):
    model = ProjectBlacklist
    template_name = "quote_manager/project_blacklist_update.html"
    fields = [
        "project",
        "reason",
    ]

class ProjectBlacklistDeleteView(DeleteView):
    model = ProjectBlacklist
    template_name = "quote_manager/project_blacklist_delete.html"
    success_url = reverse_lazy("quote_manager:project_blacklist_list")

##### COMPANY BLACKLIST #####
class CompanyBlacklistListView(ListView):
    model = CompanyBlacklist
    template_name = "quote_manager/company_blacklist_list.html"
    context_object_name = "blacklist_company_list"
    
class CompanyBlacklistDetailView(DetailView):
    model = CompanyBlacklist
    template_name = "quote_manager/company_blacklist_detail.html"
    context_object_name = "blacklist_company"

class CompanyBlacklistCreateView(CreateView):
    model = CompanyBlacklist
    template_name = "quote_manager/company_blacklist_create.html"
    fields = [
        "company",
        "reason",
    ]
    context_object_name = "blacklist_company"
    success_url = reverse_lazy("quote_manager:company_blacklist_detail")
    
class CompanyBlacklistUpdateView(UpdateView):
    model = CompanyBlacklist
    template_name = "quote_manager/company_blacklist_update.html"
    fields = [
        "company",
        "reason",
    ]
    context_object_name = "blacklist_company"
    success_url = reverse_lazy("quote_manager:company_blacklist_detail")

class CompanyBlacklistDeleteView(DeleteView):
    model = CompanyBlacklist
    template_name = "quote_manager/company_blacklist_delete.html"
    context_object_name = "blacklist_company"
    success_url = reverse_lazy("quote_manager:company_blacklist_list")

django_rock/templates/quote_manager/quote_create.html
{% extends "base.html" %}
{% block content %}
    <h1>Create Quote Request</h1>
    <form method="post">
        {% csrf_token %}
        {% comment %} <h2>Form</h2>
        {{ form.as_p }} {% endcomment %}

        <h2>Project Select/Create:</h2>
        <select id="project-select" name="project">
            <option value="">Create New Project</option>
            {% for project in project_list %}
                <option value="{{ project.id }}">{{ project.address }} ({{ project.id }})</option>
            {% endfor %}
        </select>
        
        <div id="project-form" style="display: none;">
            {{ project_form.as_p }}
        </div>

        <h2>Quote Form:</h2>
        {{ quote_form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <script>
        function check_project_select() {
            console.log("check_project_select");
            var projectSelect = document.getElementById('project-select');
            var projectForm = document.getElementById('project-form');
            if (projectSelect.value === "") {
                projectForm.style.display = 'block';
            } else {
                projectForm.style.display = 'none';
            }
        }

        document.getElementById('project-select').addEventListener('change', check_project_select);
        check_project_select();
    </script>
{% endblock %}

django_rock/templates/quote_manager/quote_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Quote Detail</h1>
    <table>
        <tr>
            <th>Company</th>
            <td>{{ quote.company }}</td>
        </tr>
        <tr>
            <th>Contact Name</th>
            <td>{{ quote.contact_name }}</td>
        </tr>
        <tr>
            <th>Contact Email</th>
            <td>{{ quote.contact_email }}</td>
        </tr>
        <tr>
            <th>Date In</th>
            <td>{{ quote.date_in }}</td>
        </tr>
        <tr>
            <th>Contact Phone</th>
            <td>{{ quote.contact_phone|default_if_none:"" }}</td>
        </tr>
        <tr>
            <th>Date Close</th>
            <td>{{ quote.date_close }}</td>
        </tr>
        <tr>
            <th>Date Sent</th>
            <td>{{ quote.date_sent|default_if_none:"" }}</td>
        </tr>
        <tr>
            <th>Project Address</th>
            <td>{{ quote.project.address|default_if_none:"" }}</td>
        </tr>
        <tr>
            <th>Project Postcode</th>
            <td>{{ quote.project.postcode|default_if_none:"" }}</td>
        </tr>
        <tr>
            <th>Project In London</th>
            <td>{{ quote.project.in_london|yesno:"Yes,No" }}</td>
        </tr>
        <tr>
            <th>Project Work Type</th>
            <td>{{ quote.project.get_work_type_display|default_if_none:"" }}</td>
        </tr>
        <tr>
            <th>Project Value</th>
            <td>{{ quote.project.value|default_if_none:"" }}</td>
        </tr>
        <tr>
            <th>Project Contract Type</th>
            <td>{{ quote.project.get_contract_type_display|default_if_none:"" }}</td>
        </tr>
    </table>
    <a href="{% url 'quote_manager:quote_list' %}">Back to Quote List</a>
{% endblock %}

django_rock/templates/quote_manager/quote_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Quote Requests</h1>
    <table>
        <thead>
            <tr>
                <th>Company</th>
                <th>Contact Name</th>
                <th>Contact Email</th>
                <th>Date In</th>
                <th>Contact Phone</th>
                <th>Date Close</th>
                <th>Date Sent</th>
                <th>Project Address</th>
                <th>Project Postcode</th>
                <th>Project In London</th>
                <th>Project Work Type</th>
                <th>Project Value</th>
                <th>Project Contract Type</th>
            </tr>
        </thead>
        <tbody>
            {% for quote in quote_list %}
                <tr>
                    <td>{{ quote.company }}</td>
                    <td>{{ quote.contact_name }}</td>
                    <td>{{ quote.contact_email }}</td>
                    <td>{{ quote.date_in }}</td>
                    <td>{{ quote.contact_phone|default_if_none:"" }}</td>
                    <td>{{ quote.date_close }}</td>
                    <td>{{ quote.date_sent|default_if_none:"" }}</td>
                    <td>{{ quote.project.address|default_if_none:"" }}</td>
                    <td>{{ quote.project.postcode|default_if_none:"" }}</td>
                    <td>{{ quote.project.get_work_type|default_if_none:"" }}</td>
                    <td>{{ quote.project.value|default_if_none:"" }}</td>
                    <td>{{ quote.project.get_contract_type|default_if_none:"" }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'quote_create' %}">Create Quote</a>
{% endblock %}